plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: <Steve Vaughan>
summary: <It is a site to promote my new book.>
lang: en
locale: en_GB
url: "https://<your domain name>"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20